[project]
name = "pleasesboss"
version = "0.1.1"
description = "Pleases Boss's WebEx Chatbot"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.0.3",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
]
